export const Report_in_Issue_Tracker = [
    "#",
    "MCPS Project ID#",
    "BU#",
    "Version",
    "Region",
    "Market",
    "Market Area",
    "USID",
    "Structure Type",
    "Site Id",
    "Site Name",
    "Remarks",
    "Remarks Date",
    "Status",
    "Resolve Date",
];

export const Daily_Tracker = [
    "#",
    "BU#",
    "Version",
    "Region",
    "Market",
    "USID",
    "Site ID",
    "Lat",
    "City",
    "Market Area",
    "Structure Type",
    "Site Name",
    "Long",
    "Zip Code",
    "State",
    "Property Owner",
    "Country",
    "Pace Job",
    "RFDS Technology",
    "Desktop Modeler",
    "RM Assign Date",
    "Report Maker Name",
    "RM Complete Date",
    "QA Assign Date",
    "QA Engineer",
    "QA Complete Date",
];
export const Site_List = [
    "#",
    "MCPS Project ID",
    "BU#",
    "Version",
    "Market",
    "Region",
    "Address",
    "City",
    "state",
    "Zip",
    "Latitude",
    "Longitude",
    "Structure Type",
    "SOW",
    "Requested By",
    "Listed_by",
    "Site status",
    "Actions",
];
export const Customer_Site_List = [
    "MCPS Project ID",
    "BU#/Configuration",
    "Request Type",
    "Site Classification",
    "Market Name",
    "ETA Selected",
    "PE Stamp Service",
    "Request Date",
    "Project Live Status",
    "ETA",
    "POR Details",
    "PO Details",
    "Report Details",
    "Approval Date",
    "GR Receival Date",
    "Invoice Details",
    "Action",
];
export const Site_Cancellation = [
    "#",
    "Region",
    "Market",
    "Usid",
    "Fa Number",
    "Version",
    "Site Id",
    "Site Name",
    "City",
    "state",
    "Site Status",
    "Actions",
];
export const Antenna_Spec_Sheet = [
    "#",
    "Antenna Make",
    "Antenna Model",
    "Antenna Class",
    "Antenna Sub-Model",
    "Antenna Type",
    "Frequency (MHz)",
    "Gain (dBi)",
    "Aperture (ft)",
    "HBW (deg)",
    "Min EDT (deg)",
    "Max EDT (deg)",
    "AZ_Offset",
    "Gain (Special)",
    "HBW (Special)",
    "RM Antenna Pattern",
    "IXUS Antenna Parameter",
    "Validated By",
    "Validated At",
    "Action",
];
export const Radio_Spec_Sheet = [
    "#",
    "Radio Make",
    "Radio Model",
    "Radio Type",
    "Frequency (MHz)",
    "Band",
    "Radio Max Rated Power (dBm)",
    "Radio Max Rated Power (W)",
    "No of Tx/Rx Ports",
    "Operation Mode",
    "Band Max Power (dBm)",
    "Band Max Power (W)",
    "Tx Power per port (W)",
    "Comments",
    "Validated By",
    "Validated At",
    "Action",
];

//QA Team

export const TableHeader1 = [
    "#",
    "Status",
    "BU#",
    "Version",
    "Market",
    "Region",
    "Structure Type",
    "Comments",
    "Rejection type",
    "Report approval",
    "Action",
];
export const TableHeader2 = [
    "#",
    "Status",
    "BU#",
    "Version",
    "Market",
    "Region",
    "Structure Type",
    "Comments",
    "Rejection type",
    "Report approval",
    "Rejected By",
    "Action",
];

//Report Team

export const TableHeader3 = [
    "#",
    "Status",
    "BU#",
    "Version",
    "Market",
    "Region",
    "Structure Type",
    "Action",
];
export const TableHeader4 = [
    "#",
    "Status",
    "BU#",
    "Version",
    "Market",
    "Region",
    "Structure Type",
    "Rejected By",
    "Action",
];
export const Master_Site_List1 = [
    "#",
    "BU#",
    "Version",
    "Market",
    "Region",
    "Structure Type",
    "Actions",
];
export const Master_Site_List2 = [
    "MCPS Project ID",
    "Address",
    "City",
    "state",
    "Zip",
    "Latitude",
    "Longitude",
    "SOW",
    "Requested By",
    "Listed_by",
    "Site status",
    "Status",
    "Comments",
    "Rejection Type",
    "Report approval",
];
