export const sampleAPIResponse = {
  status: "200",
  description: "success",
  data: {
    userId: "244",
    role: "2",
    userType: "Internal",
    email: "devuser@gmail.com",
    roleText: "Field Team",
    name: "Developer",
    apikey: "0d93cacd9d7615137242079e2fe81ef2",
    lastLogin: "2024-03-18 21:23:06",
    isLoggedIn: "1",
    isOTPVerified: "yes",
    isTestUser: "0",
    comapnyname: "1",
    operatorId: "1",
    moduleId: "10",
    regionMarketString: [],
    moduleFolderName: "att/main_onsite/",
    siteInfoTable: "mep_siteinfo_att_main_onsite",
    siteInfoMappingTable: "mep_user_siteinfo_mapping_att_main_onsite",
    siteSurveyTable: "site_survey_att_main_onsite",
    surveyLogsTable: "survey_logs_att_main_onsite",
    surveyMeterReadingTable: "map_site_survey_meter_rading_att_main_onsite",
    siteHistoryTable: "tbl_site_history_att_main_onsite",
    siteExtraInfoTable: "site_survey_extra_info_att_main_onsite",
    reportArrangeTable: "report_arrange_att_main_onsite",
    rfsapArrangeTable: "rfsap_arrange_att_main_onsite",
    reportTable: "survey_file_report_att_main_onsite",
    rawDataTable: "tbl_survey_raw_data_att_main_onsite",
    notificationTable: "notification_att_main_onsite",
    surveyDefinitionTable: "sitesurvey_table_definition_att_main_onsite",
    siteSurveyPhotosTable: "site_survey_photos_att_main_onsite",
    rmReportVersionTable: "tbl_rm_report_version_att_main_onsite",
    qcReportVersionTable: "tbl_qc_report_version_att_main_onsite",
    qaReportVersionTable: "tbl_qa_report_version_att_main_onsite",
    pcSchedulerMappingTable: "pc_scheduler_mapping_att_main_onsite",
    fscSchedulerMappingTable: "fsc_scheduler_mapping_att_main_onsite",
    roofmasterTable: "",
    surveyIssueTable: "",
    rfdumpTable: "rfdump_att_main_onsite",
    rmAssemblyMappingTable: "rm_assembly_mapping_att_main_onsite",
    isRadioValidator: "0",
    isAntennaValidator: "0",
    rfdumpAddOnTable: "",
    buildingInfoTable: "building_info_att_onsite",
    operatorMasterTable: "tbl_operator_master_att",
    financeVendorDataTable: "",
    preEmeDeliverableTable: "tbl_pre_eme_att_main_onsite",
    otherRFDumpTable: "other_rfdump_att_main_onsite",
  },
};
